name: CI - API Data e Hora

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Executar testes
        run: npm test

    # 🔹 JOB 2 — DOCKER
  docker:
    runs-on: ubuntu-latest
    needs: test   # 👈 só roda se o test passar
    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: construir imagem Docker
        run: docker build -t api-data-hora .