name:pubicar imagem no GHCR

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test